# Generated by Django 3.2 on 2021-04-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_rename_vote_vote_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='polls',
            field=models.BooleanField(default=False),
        ),
    ]
