# Generated by Django 3.2 on 2021-04-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_vote_polls'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='polls',
            new_name='vote',
        ),
    ]
