# Generated by Django 3.2 on 2021-04-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_rename_polls_vote_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='Name',
        ),
    ]
