# Generated by Django 3.2 on 2021-04-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voting', '0006_delete_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('no_of_votes', models.IntegerField(default=True)),
            ],
        ),
    ]
