# Generated by Django 3.2 on 2021-04-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='vote',
            field=models.BooleanField(default=False),
        ),
    ]
