# Generated by Django 3.2 on 2021-04-15 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_poll_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='no_of_votes',
            field=models.IntegerField(default=0),
        ),
    ]
